### ISSUE TITLE
BUG(PROD): Cannot reset unverfied account password 

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1008]
**Describe the bug**
Cannot reset Alkemio account password.

**To Reproduce**

1. Go to https://hub.alkem.io/identity/recovery?
2. Enter your Alkemio email account
3. From the received email use the link to change the password
4. Save the changes
5. Sign out
6. Sign in with the new password - **Authentication fails**

**Expected behavior**
Reset password flow works for all domains.

**Additional context**
Authentication works with the old password.

The issue is not reproducible with **gmail** and **yahoo** accounts.

**Comment by atstojanov** [comment]
I've tested it on https://hub.alkem.io by creating new account with my alkem.io email and I've successfully changed my password.

**Comment by valentinyanakiev** [comment]
The issue is not with @alkem.io accounts per se, the issue is with accounts that we 'cleansed' with the script that I said was borderline dangerous and is likely to have side effects as we don't know all the caveats of the system. Long story short, account recovery on any identity that has traits without "accepted_terms" fails. I tested with my account locally, and updated the table identities, the field traits of my account with "accepted_terms": true and it worked like a charm. We need to run a 2nd script now on the database that matches & updates identities.traits json and adds "accepted_terms": true|false .

**Comment by valentinyanakiev** [comment]
SELECT * FROM kratos.identities where traits not like "%accepted_terms%";
That query yields 24 results - all the messed up identities that will have problems.

**Comment by valentinyanakiev** [comment]
That script should fix it:
SET SQL_SAFE_UPDATES=0;
UPDATE kratos.identities set traits = JSON_SET(traits, "$.accepted_terms", "true") where traits not like "%accepted_terms%";
SET SQL_SAFE_UPDATES=1;

I suggest Evgeni double checks for side effects and we proceed with it.

**Comment by Comoque1** [comment]
The script works fine, for the case, when the user doesn't have `accepted_terms` parameter at all.
In case `accepted_terms` is `null` or `false`, it will not work. PROD db, needs to be double checked for the data, if such users exist.

Running the script and resetting the password, works fine.
