### ISSUE TITLE
Ensure the client has the latest data for Updates (via subscriptions)

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1507]
## Description

As a user I want near real time updates if messages come through on a update where I am a member + navigating

As a user I want that the client presents the actual data

## Acceptance criteria

- [x] Updates: when another user sends an update you should receive it and then any displays using that data should use the correct latest data (including counters) in the dashboard preview panel, community page, admin page (updates)
- [x] Ensure the client cache is updated

## Additional Context

Enable subscriptions on Dev

**Comment by hero101** [comment]
Because of the second message coming through the application crashes on deletion of one of them

![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/febe3ae6-5746-4709-9a64-907047f65bb6)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/d8efcf18-1bdd-488b-b6ae-2925db316275)

**Comment by techsmyth** [comment]
Can you please describe the steps to reproduce the above issue?

**Comment by hero101** [comment]
@techsmyth I believe it's due to the client displaying two messages for the poster, when he posts and update.
When they try to delete the message which has its id starting with `~!` and contanining the hostname (the screenshot above) this error is thrown.
This will probably will be resolved with the server sending the proper message or the client having some optimizations made on the admin updates page.

**Comment by techsmyth** [comment]
so the messages have different ID's in different questions? Will try to ping you later...

**Comment by Comoque1** [comment]
After exploring the subscriptions using the client, I decided to move it back to backlog due to:
 - When sender sends an update - it is generated twice
 - Sender gets an information alert ("You just received an alert")
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cadf28d9-7841-4174-bd0c-21c786795c5e)
   - If intend to delete and start from the second message, error is thrown
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/00fb6c0a-2a0d-4255-9211-b3e5042f46be)

In addition - when update is removed or edited (editing update is not available at the moment), notifications must be sunt to the rest of the user that are subscribed.

**Comment by techsmyth** [comment]
Closing this as there is now a new issue for switching to the new subscriptions ap: https://github.com/alkem-io/client-web/issues/1646
