### ISSUE TITLE
BUG: Global search term is not cleaned, after user navigate to another page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#1555]
**Describe the bug**
Global search term is not cleaned, after user navigate to another page

**To Reproduce**

1. Go to https://dev.alkem.io/
2. In the global search type: "test" - user is redirected to search page
3. Click on "Home" page - user is redirected successfully, but the search term remains
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/016794ba-6749-489b-ac00-ad91a2008b69)

**Expected behavior**
Global search terms are removed after user hits enter.

**Comment by me-andre** [comment]
I've slightly altered the expected behavior: the search input stays when the user is taken to the search results page (purpose: user is able to correct his search query). However, when he navigates to any other page, the input gets cleared.
Also, when a user navigates to the search results page by typing in the address bar, the input is initialized with the value from the query string (for consistency).
