### ISSUE TITLE
Display challenge / opportunity count

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1656]
## Description

As a user I want to understand that there are additional challenges / opportunities on dashboard pages

## Acceptance criteria

- [ ] Show the total count of Challenges / Opportunities - Challenges [X number] 

## Additional Context

Use the activity query. E.g.

```gql
query hubs {
  hubs {
    nameID
    activity
    {
      name
      value
    }
 
  }
}

```

Activity query can be used on hub, challenge, opportunity for the required data.
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/2ecf1051-2851-4797-8bc1-c658c020805c)

Opportunities in the context of the Challenge
Challenges in the context of the Hub

**Comment by valentinyanakiev** [comment]
![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/77e8c6b8-0c1c-4ac9-b58c-38a21ee9497f)

**Comment by me-andre** [comment]
To be able to reliably access challenges/opportunities count from a dashboard component, I added some metadata to the activity prop (ActivityItem[]). This doesn't look as an elegant solution, but the problem is slightly deeper - we pass pre-formatted data from containers (translations applied), which, to my belief, we shouldn't do. I think we should consider changing the format activities are passed
from containers to the underlying consumer components.

**Comment by Comoque1** [comment]
Looks OK on Test env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ee0ee6dd-aee6-48f2-9eb0-e219d5ecb895)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d0c5e216-4d07-493f-8d66-cf300f899f37)
