### ISSUE TITLE
React Router v6 migration

### ISSUE THREAD

**Issue by atstoyanov** [alkem-io/client-web#1684]
## Description
Migrate all existing routes to react-router v6.

## Acceptance criteria

- [ ] Reacto-router is updated to v 6.
- [ ] Navigation is working
- [ ] Tabs are working

## Additional Context
The React Router has been updated to V6.
Most routes have been updated to use the new syntaxis.
The `App.tsx` now works as a layout.

The `EcoverseTabsNew.tsx` and `EcoverseRouteNew.tsx` contain examples of how the tabs can be used as layouts. Unfortunately, I couldn't find a way to change the parent layout for nested routes which will lead to having 2 rows of tabs for challenges and 3 rows of tabs for opportunities.

**Comment by Comoque1** [comment]
Routing issues
- [ ] Ecoverse / Dashboard 
- All "see more" and "see all" redirects to 404
- Clicking on discussions redirects to 404
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/622945cf-34f0-493c-a1db-3fb6d8b98063)
- [ ] Ecoverse / Discussions 
 - When open a discussion, the underlined tab is "Dashboard " instead of "Discussions" or open [new discussion page](https://test.alkem.io/un-sdgs/community/discussions/new)
 - When create new discussion - redirects to 404
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/05994652-06e6-4e59-a024-52aab3a761e7)

- [ ] Challenge / Dashboard 
 - "Apply" button (when user has application to hub, already) redirects to 404
 - All "see more" and "see all" redirects to 404
 - Clicking on discussions redirects to 404
 - Clicking on "No discussions available" link
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f24a0cbb-e905-4b18-8bc5-48209a83e04e)
- [ ] Challenge / Discussions 
 - When open a discussion, the underlined tab is "Dashboard " instead of "Discussions" or open [new discussion page](https://test.alkem.io/un-sdgs/community/discussions/new)
 - When create new discussion - redirects to 404
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/05994652-06e6-4e59-a024-52aab3a761e7)

- Navigate back (using browser back button) from admin, keeps the admin breadcrumb
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2ae6792a-7ef9-491e-ba25-debf138e94af)

- [ ] Opportunity / Dashboard 
 - All "see all" redirects to 404
 - Clicking on a project redirects to 404
- Navigate back (using browser back button) from admin, keeps the admin breadcrumb
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/65583560-b9e6-4862-9ad6-6c36ac8efa62)


- [ ] Global search - failing to load data (https://test.alkem.io/search?terms=test)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0312b2f4-39cd-4b80-b5c5-c583e22bd2e9)

**Comment by Comoque1** [comment]
Signup page is empty
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6484d36e-15ea-42d1-8c50-e12448bfb129)

**Comment by Comoque1** [comment]
On home page "Alkemio and You" panel, links on lat paragraph are open on same tab, instead on new one.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/da04378d-6966-4279-a772-28e50bb2a044)

Openning a project from opportunity/dashboard page, redirects to 404
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a4cc95fc-d267-474d-be4c-23d8cc9b071f)

Verification flow fails.
Navigation to "https://test.alkem.io/identity/verify" also fails
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/20a7b534-5114-473e-8487-b7e24a15d3e5)

**Comment by Comoque1** [comment]
Admin area

- [ ] Missing button to add members on [Challenge and Opportunity and Organization group ](https://test.alkem.io/admin/hubs/111/challenges/1111/community/groups/bdf7438a-f03d-480f-96b1-a3be846ee2d7)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ed9274af-8458-4502-9d30-2d7785c9e14b)

**Comment by Comoque1** [comment]
Looks OK on Test env.
