### ISSUE TITLE
Explanation headers on all admin tabs

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1955]
## Description

As an admin I want to understand what I can do with each tab in the administration setion

## Acceptance criteria

- [ ] Explanation text on all admin tabs, backed up by translation file; text to be generic + later refined

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/d8e6b035-23ec-4182-a7e2-07ce1d70b1b7)

**Comment by Comoque1** [comment]
@techsmyth , shouldn't this message: `Here you can edit opportunities for this hub.` state `challenge` instead of `hub`?
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a1d60d47-649c-4b5e-995e-db270596a919)
Added a [story](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/board) to address the translations
