### ISSUE TITLE
BUG: Hub page is loading all users with full profile details - twice

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2115]
**Describe the bug**
The time taken to load the hub page on digicampus is taking 6+ seconds. 

**To Reproduce**
Login to Hub
Click on the Digicampus page while having the graphql network explorer open
All 72 users are full loaded - twice - with their full profiles:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/0a1a3bef-f18a-4808-96b7-aad794b8fcdd)

The full set of users is loaded twice: 
- hubCommunity
- hubPage

**Expected behavior**
Only the selection of users shown on the page is loaded, not all the users. 

This looks to be a regression that was introduced with the panel for contributors.

**Comment by techsmyth** [comment]
@me-andre great this is better now. I will add a separate issue re pagination on contributors as we will need that...am curious what the performance is after this update...

**Comment by Comoque1** [comment]
Moving back in progress, due to:
- [ ]  `hubCommunity` request is triggered twice.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ff218d1a-4b86-4b0b-9e8f-0eefaa1fc028)
- [ ] `hubCommunity` and `hubPage` requests both return the community members
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/15151cf9-5baf-4899-a366-f9c68afc40f1)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/468c7197-7b2d-448e-898c-9768ab0c0536)

**Comment by Comoque1** [comment]
The users now are requested only ones as part of entityPage request.
Raised another bug regarding  duplicated community request for all entities: BUG: hubCommunity, communityChallenge and communityOpportunity requests are executed twice #2136
