### ISSUE TITLE
BUG: Missing client side error message for tagline length

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2211]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/admin/hubs/16-06-2022-hub/profile
2. Authenticate with GA
3. Set Tagline with the following text:
```
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five cent
```
4. Press "Save" button - there is no error next to input field
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1f0a4d88-0e23-4dfd-9eb5-439cbbcc38f7)
5. Error message from server is not displayed on the client as allert
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4e74672f-17be-4dcd-9c87-55ab970a81b7)

**Expected behavior**
Context.tagline DTOs (create, update) have a length limit of TAGLINE_LENGTH = 120 characters
Client to enforce this limit as validation before sending the form. 
Client to display the character limit as well as current count of characters

Note: database field size is NOT updated as part of this issue, so data is not lost.

**Comment by ccanos** [comment]
Moving this task to Blocked because: 
Here it says that the DTO should be SMALL_TEXT_LENGTH which is 128 chars
In the code, the DTO is MID_TEXT_LENGTH = 512 chars
In the database the column has 255 chars which is not in any constant.

The agreed approach is to reduce the column size to 128 chars, change the DTOs to SMALL, and also add a clientside limit.

=====
REASON TO BLOCK IT:
First we need to see in live if there are any context with a tagline longer than 128 characters:
```sql
SELECT *, LENGTH(tagline) FROM alkemio.context WHERE LENGTH(tagline) > 128;
```

**Comment by techsmyth** [comment]
@valentinyanakiev this one is good to go - can you please put it in motion when you can?
