### ISSUE TITLE
BUG: When checking a canvas in / out repeatedly, the "checkedOutBy" field may not get set, which confuses the client

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2243]
**Describe the bug**
Checking the canvas in + out repeatedly can result in the checkedOutBy field not being set despite the canvas being checked out. The client then does not show the button to checkin.

**To Reproduce**

1. Go to https://dev.alkem.io/un-sdgs2/canvases
2. On 2 browsers authenticate with 2 users and navigate to the page above
3. One of the user creates a canvas
4. Both user must have the canvas open
5. I.e. User1 makes an update
6. User1 saves the change and stops editing, very fast the User2 clicks on Edit button - error is thrown and the canvas becomes locked for both users.

### Note
The issue is reproducible sometimes, and we don't have the exact steps to reproduce.
This is a client issue:  it is possible to checkin the canvas using the graphql api. It is that the client is not showing the button to check-in, potentially as it does not see that the canvas is checked out to someone?

### Expected behavior
The client to use the MyPrivileges to determine whether to show the checkin button

**Comment by ccanos** [comment]
I have pushed a branch called lifecycles-race-condition to server repo
I am convinced this issue is caused because of a race condition when triggering the lifecycle state machine and not waiting for it to resolve it, there was even a comment there in the code.

I have added a lot of console logs and now with the delay of logging it almost always reproduces the issue.

I have tried many things but I ran out of time. 
Looks like the solution is something like returning a promise and resolve it in the onDone property of the machineDefinition.
I need someone with more experience in the server to take a look with me to this.

Some documentation:
https://stackoverflow.com/questions/70153364/xstate-how-to-return-from-data-from-interpretmachine-ondone
https://stackoverflow.com/questions/56455430/xstate-wait-for-response-of-invoked-function

https://github.com/statelyai/xstate/discussions/1749
https://xstate.js.org/docs/guides/events.html
https://xstate.js.org/docs/guides/communication.html#invoking-promises
https://xstate.js.org/docs/guides/introduction-to-state-machines-and-statecharts/#actions

**Comment by techsmyth** [comment]
Yes it is very clear and a known issue that there is a race  condition on the server. This issue was not about that but dealing with it better on the client. We talked about this and the expected behavior is clear.
