### ISSUE TITLE
BUG: Comments scroller on FF is not the expected one

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#2567]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/comments-hub/challenges/comments-challenge/opportunities/comments-opportunity/explore/callouts/card-default/aspects/1111-8815/dashboard
2. Comments scroller is not the one applied for Chroimium based browsers
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/67a7b4b7-0e5f-4961-87e5-1e586393d285)

FF version: 104.0.1 (64-bit)

**Expected behavior**
Comments scroller on FF is same as Chromium based browsers.

**Comment by ccanos** [comment]
I've done a little investigation, and looks like customizing scrollbars the way we do it is not supported by firefox because it's not a standard yet.
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

There is a supported way, but it's way more limited:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars
Only allows to change the color, and the width two but only between a set of predefined values...

I've played a bit with it on [this fiddle](https://jsfiddle.net/vwao41fh/) and got to have an 'okay' result... 
Just needs this change
`scrollbar-color: #068293 rgba(255, 255, 255, 0);`
