### ISSUE TITLE
Spike: usage of wysiwyg markdown component

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2780]
## Description

As a user I want help with formatting my text in a simple and appealing way, so that it is What you see is what you get (WYSIWYG)

## Acceptance criteria

- [ ] Demonstrate usage of a WYSIWYG markdown editor within the client e.g.  https://jpuri.github.io/react-draft-wysiwyg/#/
- [ ] Ability to control how images / documents uploaded using this editor are handled
- [ ] Ability to use emoticons
- [ ] Compatible OSS license 
- [ ] Current data can be rendered in the new component

Note: an alternative is https://github.com/outline/rich-markdown-editor

Evaluate a couple of candidates the meet the requirements

**Comment by hero101** [comment]
Is this component based on any predefined requirements? If yes, can you please share them?

**Comment by ccanos** [comment]
Alternatives:
All of these wysiwyg editors internally have a structure that holds the pieces of text+styles as blocks... that structure can be exported to json but the typical use case is to export it to HTML. 
I have made this investigation with the premise that: We don't want HTML.
- Letting users post their own html breaks the pages, is messy and can be dangerous
- All our current content is in Markdown
Investigated Quill and Slate, didn't get to test them, they both look very promissing but too powerful, they have plugins to export to markdown but I didn't see any good demo of them using Markdown/migrating to markdown. 
The one I have ended up using is the one suggested in the task because it's based in DraftJS and had some clear demos of markdown usages.

**Comment by ccanos** [comment]
Conversion 
- Whatever Editor we find HAS to have Markdown <-> (Editor's Internal Structure) bidirectional conversion. 
- The MD generated should be compatible with our current MD renderer https://github.com/remarkjs/react-markdown
- The conversions should not break the text (I format some text, I save, and when I refresh the page I should see exactly the same in the wysiwyg editor)

I have found many NPM packages doing the conversion from the DraftJS Estate Object to Markdown and back but it's not trivial and some work better than others. 
I have chosen one that does a really good job but still cannot use it as-is:
https://www.npmjs.com/package/markdown-draft-js
It's one year old, but there are newer forks:
https://www.npmjs.com/package/@beincomm/markdown-draft-js
And has some forums in the github issues, I've seen many things solved there and a lot of movement.


These two are very promissing but I couldn't make them work:
https://www.npmjs.com/package/draft-js-import-markdown
https://www.npmjs.com/package/draft-js-export-markdown
DraftJS was throwing an exception, if I have some more time I'd like to investigate them.


I have included some files from markdown-draft-js with the changes made by @beincomm/markdown-draft-js and a few more that I found in the github issues to support images and emojis into our code. 
I need a place to store them properly or decide what we do with them, for now I haven't found a perfect bidirectional converter but I think we can get to have it basing on these ones.

**Comment by ccanos** [comment]
Emoticons
The database is not saving the emojis UTF chars correctly. Not sure why, I see wrong chars in MySQL workbench and the chars are returned by the db as "?????"
I'm have tried translating those UTF chars to html entities and that works nicely. Things like &#x1F601; 
Ironically the markdown renderer doesn't handle those entities correctly and I have to unencode them, but I'd like to have a bit of time to investigate that and make it work.

**Comment by ccanos** [comment]
Image upload
The API of this Editor is very simple. Supports adding an image by url and also provides a little dialog with a file form field. When the user pushes there an image a callback is executed that should return a promise that will resolve to the url of the image.
Problems:
- We wanted to show a message to the users saying something like "you are responsible for what you upload" - Easy to fix
- The Editor supports aligning the image (Left/Center/Right) and setting its size which will afect the visualization in the form but that is not "translatable" to markdown so that information will be lost. We need to remove that functionality.

**Comment by ccanos** [comment]
MaxLength
The maxLength and in general the text length can be problematic, because whatever the user types is translated to markdown which may not have the same length. 
But it's a common problem with all of these editors, none of the others have a maxLength implementation, only tricks I've seen in their github repos.
We definitely can calculate the total length of the resulting markdown on every keypress and on every action (pasting/changing the styles/... can increase the size in more than 1 char at once), but it's not trivial to prevent action and loading a previous state hasn't worked well in my tests.
One easy solution -last resort- would be to prompt the user on submit and say "hey your text is going to be truncated".

**Comment by ccanos** [comment]
Other than that, as I said, the editor suggested is very good. Allows localization(translate the toolbar), allows tagging people with the @ in the future, the image handling is alright, I have customized it to look exactly like our other material text fields without much effort...

**Comment by ccanos** [comment]
https://github.com/alkem-io/client-web/pull/2818
