### ISSUE TITLE
BUG: Sign up button from home page takes user to wrong endpoint

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#3103]
**Describe the bug**
Theis may not be an actual bug, but the flow for user registration, should redirect the user to same page with same content.

**To Reproduce**

Flow 1
1. Go to https://acc.alkem.io/
2. Click on "Sign in" button -  redirect to https://acc.alkem.io/identity/login?returnUrl=/
3. Click on 'Click here to sign up.' link -  redirected to https://acc.alkem.io/identity/sign_up
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e1a04037-6587-4e26-a772-d2f17acb1b8d)

Flow 2
1. Go to https://acc.alkem.io/
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0ddf1077-5678-4d2a-9eb9-1bc27bb2526c)
2. Click on "Sign up" button - redirects to https://acc.alkem.io/identity/registration
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a4d6c0e1-d4f0-4224-97b1-40b59b85bd9f)

**Expected behavior**
When user click 'Sign up' button, he is redirected to https://acc.alkem.io/identity/sign_up

**Comment by valentinyanakiev** [comment]
I don't see a bug here, and I don't believe that is the expected behavior. There are 2 separate pages needed:
- Sign Up, for the user to select how to Sign up https://acc.alkem.io/identity/sign_up
- Registration, for email:password flows, **selected in the Sign up page**, navigating to https://acc.alkem.io/identity/registration
