### ISSUE TITLE
BUG: Resolution header images journey pages too low

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#3425]
**Describe the bug**
When I try to upload a header image on a hub, it looks ugly like the resolution is too low. 

Image:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/37cf088a-f1b0-4b23-b157-65861034fbc7)

In Hub:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/a5a4ce4c-5307-4fcf-a810-1e7051d59f62)

**To Reproduce**

1. Go to a hub where you have admin rights
2. Add a nice image with a good resolution
3. See how it's being destroyed ;-)

**Expected behavior**
A sharp header image
I think the resolution when scaled down should be at least 1400*180?

**See comment below**

**Comment by ccanos** [comment]
Needs a change in here:
[domain/common/visual/visual.service.ts :148](https://github.com/alkem-io/server/blob/develop/src/domain/common/visual/visual.service.ts#L148)
But also needs a I think the fix should be a migration changing the max-width of all the visuals `banner`, or make the image cropper tool take the expected dimensions from somewhere else (some platform configuration? or hardcode them in the client? ) because at the moment it is expecting (and cropping) an image of the same size as the current image.

**Comment by techsmyth** [comment]
@ccanos we can easily update that value in the server, as agreed that it is simply too low. This should be a very simple migration to do...
