### ISSUE TITLE
Add community tab

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3706]
## Description

As a visitor of the Hub I want to immediately see who is involved in this community as it is one of the most important elements of the Hub

## Acceptance criteria
- [ ] Community tab added
- [ ] About leads /host moved to Community tab, plus button to connect to leads
- [ ] Activity block block with 3 entries
- [ ] Blocks for users + organizations with switch on user / organization + option to search
- search can be used from whiteboard templates (component)
- users and organizations both visible (if possible random) 
- 4 rows max, more is scroll
- [ ] Add subscriptions if not component-based

## Additional Context
https://www.figma.com/file/zw3ymZPkFkVqtMsVLRuLRR/Structure-refresh-Q1?node-id=263%3A1428&t=qv9KmOqfaZ9jxNEk-1
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/b58d3a89-eb3c-4429-a30d-d33ca9995f07)

Note that Callouts in context are included as part of #3698

**Comment by Comoque1** [comment]
After exploring the Hub / community tab, the following points have been identified:

1. 'Who is involved' component
  - only 1 row of users is displayed, instead of 4 as per AC
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ebf51553-fd2f-44ff-9372-1aec4f656977)
  - on iOS, browser : Safari the search component is not correct - must be 'magnifier' icon
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b3deb341-9d83-4399-aa2c-477bcf5be8c8)
   - on apple and android mobile device, when click 'Show all' - the dialog is not resized and user has no option to close it or see all the data
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3fa47fdf-288d-4f00-93b6-7572715048bc)
  -  after clicking on 'Show all' button - the dialog, doesn't show all members
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/60f9a35a-558b-47c8-aac5-3ea4dbfd07a9)

**Comment by Comoque1** [comment]
When add card callout using group1 on community tab, the activity log data is removed
1. Go to https://dev.alkem.io/callouts2/community
2. Assign a user to the community - user is added successfully, and is is visible on community tab activity panel
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/00ef3996-f0a3-4abe-8b3d-b42b3172d936)
3. Add card callout - the activity log loose its data
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/34dd2836-ef86-4540-9be2-b002a50c2d7f)

**Comment by Comoque1** [comment]
The number of Users / Organizations displayed on expanded component is not full:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/238df9a8-3465-47f5-9f03-41c921c4d6b6)
