### ISSUE TITLE
Filter Challenges on tags

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#3772]
## Description

As a user, I want to use Challenges to work on real Challenges, not to use them as themes and then Opportunities as Challenges.

I also want to filter the Challenges in a Space based on a theme.

## Acceptance criteria

- [x] Visualize tags on the Challenges page so users can filter the Challenges
- [x] Clicking on tag adds the tag to the search box
- [x] tags derived from the tags used in the challenges
- [x] All tags visible, aligned to the right (if more, two lines)

## Additional Context

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/e71b2ee0-91bf-4542-bc28-8dd3d348ae09)

**Comment by SimoneZaza** [comment]
Nice nice nice! Just 2 things:
- When a tag is used twice, but with different cases, both are displayed in the tagset. Would be nice to just show 1 (can be random which one)
- On mobile, the search bar is very narrow and grows out of reach when tags are entered. Would be nice to display the search bar below the title of the block instead of next to it, and if possible, for in not to grow outside of the block (max of 4 columns, like the other content)
