### ISSUE TITLE
BUG: Comments get lost in FORUM

### ISSUE THREAD

**Issue by MayteRagni** [alkem-io/client-web#3785]
**Describe the bug**

When adding a comment under one of the questions in the forum the message got lost in the moment of publishing and then a sign saying "unauthenticated message" appeared. 

Spike: timebox to half a day to find out what is happening

**Screenshots**

![image.png](https://images.zenhubusercontent.com/633ac68dc0aaa9f52e6ca9a6/dd4fd04c-4957-471d-9d97-fd96016ef092)

**Additional context**

**Comment by MayteRagni** [comment]
However, after refreshing the page a few times the comment was back, still should not happen. Good to look into it

**Comment by techsmyth** [comment]
@MayteRagni not just on forum, this is happening also a lot on comments in general, and it is a killer for interactive sessions

**Comment by hero101** [comment]
All my findings revolve around `OryStrategy.validate`.
The validation flow goes as follows:
1. if there is no session, stop there and create an empty auth info object so the request is progressed further and can fail at any time if the access criteria are not met.
1. if a session is found, check the JWT token expiry - if it's expired fail the request
1.  if the JWT has not expired create an agent info object based on the session identity

The mentioned exception is thrown on the second step. There are no other accounts of the same error message.
As soon as a resolver is validated using a guard - the guard is calling the `validate` method of the defined strategy(OryStrategy). When this exception is thrown and bubbles up through the WebSocket connection, which is closed on an error. The path is as follows:
- resolver -> graphql.guard -> (calls OryStrategy.validate) -> (throws) -> graphql.guard.handleRequest handles -> bubbles back to the resolver -> sent to the client through ws

The bizarre part is the changes to have a session but an expired JWT token are slim to none.
To counteract the problem we have made the earliest time to extend the session to half of the session's life.
The problem is not fixed but may be reduced. We wIll continue to monitor the problem.
