### ISSUE TITLE
BUG: Tag data is cut for resulted users on community page

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#386]
**Describe the bug**
Tag data is cut for resulted users on community page.

**To Reproduce**

1. Go to to [momentum acc env](https://acc.odyssey.ninja:3000/community)
2. Authenticate
3. Navigate to "community" page
4. Apply the following search params: "test", "ai", "front-end-decelopment", "good"

In the results, where a user has both: "ai" and "front-end-decelopment", the second tag is cut.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6bf8a016-34af-492a-9e00-8c78cc6bfd59)

**Expected behavior**
The tag should be visible or truncated and tooltip with full information must be displayed.

**Comment by OlegSubik** [comment]
because tags are displayed in the user card and text is not predictable there is a problem of lack of space. Issue is that we cant predict the length of a matched tag. I've tried various options and here are the best results out off all.

1. 
get rid of "mathed terms" text 

 ![image.png](https://images.zenhubusercontent.com/5f9c20ca91c6228710eb978a/4ca31a5f-591f-4ac0-8e3c-722297966038)

2.
try to fit it (squise everything)

 ![image.png](https://images.zenhubusercontent.com/5f9c20ca91c6228710eb978a/cd290312-de3b-4a9a-868e-8db21b80e464)

3.
keep "Matched terms" and move tags (ovals) to the tooltip after hovering text

4. 
remove  mathed terms
