### ISSUE TITLE
BUG: whiteboard templates to have visual set

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4034]
**Describe the bug**
All of the whiteboard templates in the innovation library are without a visual image

**To Reproduce**

1. Go to the innovation library and open up any innovation pack with whiteboard templates
2. the visual is missing

**Expected behavior**
The visual showing a preview of the contents of the whiteboard is shown on the card representing the whiteboard

Note: also opening up the whiteboard, editing and saving it did not result in the visual being updated. High priority as having these visuals makes a huge difference to the display.

**Comment by Comoque1** [comment]
Visual can be set to whiteboard templates: 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/80d8fe8c-748a-485e-9d7f-5ff8dca8b8a3)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/987fa9a2-2ab1-4973-a084-0c276d5b48ce)
But you are right @techsmyth, it would make more sense to have preview of the content, rather than other image.
@valentinyanakiev, @me-andre, can we address this one today or tomorrow? We already have similar behavior to canvases.
 ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e9f704c6-14a5-45eb-bb4a-484abc243235)
