### ISSUE TITLE
Expand limit on post content

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4057]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Allow 2000 characters on post content

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
The Callout description length is increased, but the post (description) is already 8000 chars length.
@techsmyth , could you please confirm, that considered the callout entity description expansion as part of this story, or the description of actual post (card)? 

In addition, with such a big content for callout description, we need to rework the visualization:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3b77949c-cb6e-4f12-bd29-3547b067c582)

**Comment by techsmyth** [comment]
@Comoque1 it should be in both cases the 8000

**Comment by Comoque1** [comment]
@techsmyth, I think we need to define better expected behavior:
 
Current implementation:
 - post (aspect) description is 8000 characters
 - call for posts (aspect callout) description and default text is 2000 characters

The acceptance criteria:
 - Allow 2000 characters on post content
 - @Comoque1 it should be in both cases the 8000: for callout in general (all types) and post (aspect) card?
