### ISSUE TITLE
BUG: Recent Contributions block to have consistent text styles

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4081]
**Describe the bug**
The recent contributions block takes different text styles for titles of callouts and whiteboards (and maybe more?). This should all be consistent, the same style as the comments and updates have.
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/14b938f5-4ceb-4592-8581-557cda87fdd2)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SimoneZaza** [comment]
@ccanos can you share your thoughts?

**Comment by ccanos** [comment]
All the entries in this list are printed through an `ActivityBaseView`
The problem is that some of the descriptions have markdown and some don't. 
The ones that have markdown are printed through a `OneLineMarkdown`, and in those case where descriptions aren't markdown the string is directly rendered.
There are a few options, not sure which is cleaner:
- Something like this code in `ActivityBaseView`:
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/79db6b0f-6b18-45b4-80bb-f86f918b3df9)
- Go through all the References to `ActivityBaseView` and add the `<Caption>{description}</Caption>` to all the ones that are not markdown.
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/e30de36c-4e88-4f91-81fc-062c43484b1d)
- ... Maybe something cleaner
