### ISSUE TITLE
Refresh assignment of community roles at challenge + opportunity level

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4208]
## Description

As a challenge / opportunity admin I want to be able to manage community menbership effectively

## Acceptance criteria
**NB** This needs to be picked up together with a refresh of the authorization/settings page

- [ ] Community management o contributors at challenge level + opportunity level using the approach from space:
- Remove the administration assignment from the authorization tab
- Assignment of roles per user / organization: user, lead, admin

## Additional Context

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/4ffb5aab-c7eb-4597-abc1-fa256c232cb8)

**Comment by alstojanovic** [comment]
@techsmyth if we are going to use x-data-grid for tables and use the `CommunityAddMembersDialog` then https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/4533 isn't a blocker for this one and can actually be closed because we will then be removing `EditMemberUsersWithPopup` component.

**Comment by techsmyth** [comment]
@alstojanovic makes sense - please update as you suggest
