### ISSUE TITLE
My Dashboard elements: Latest contributions in the Forum

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5019]
## Description
As a user, I want to see various things that are going on at the platform
As the Alkemio team, I want to spark interaction

## Acceptance criteria

- [ ] List of first 5 discussions in the forum, based on most recent activity (as currently also is shown on the forum itself)
- [ ] Exact length based on height left column in some pages
- [ ] More button to point to the forum
- [ ] Please check if it looks acceptable on mobile
 

## Additional Context
Figma: https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?type=design&node-id=550-14696&mode=design&t=rMd26aUOKrOecriT-4

**Comment by hero101** [comment]
@SimoneZaza Just to clarify - "most recent activity (as currently also is shown on the forum itself)" is **currently** not be recent activity, but the **most recent created** discussion **first**.

**Comment by ccanos** [comment]
I created this task https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/3482 to discuss about it and implement it if needed

**Comment by hero101** [comment]
Since it's based on comments stored in a saparate place and we not having efficient way of loading them, it makes it a heavy operation and not straight forward to achieve as far as I know.
Currently we implemented it as most recent discussion creation date.
If you want to prioritize the feature let us know and we can discuss.

**Comment by hero101** [comment]
@SimoneZaza Since it's based on comments stored in a saparate place and we not having efficient way of loading them, it makes it a heavy operation and not straight forward to achieve as far as I know.
Currently we implemented it as most recent discussion creation date.
If you want to prioritize the feature let us know and we can discuss. In the meantime we raised a product discussion story - https://github.com/alkem-io/server/issues/3482
