### ISSUE TITLE
Usability: Search dialog: after a search, field feels like cleared while its not

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#5082]
## Description
In Search dialog, when I enter a search term and press enter, the field itself gets cleared while functionally the "field" accumulates search terms (which can be seen from chips on the right side of the field).
For me it's counter-intuitive, I constantly forget that I have to look at the chips to see current search terms.
I'd rather remove the chips and have pure text search field that doesn't get cleared when the term gets submitted.
(The other solution could be adding tags at the start of the field as in tag inputs).

![Image](https://github.com/alkem-io/client-web/assets/594548/00fb7f05-b140-4241-a028-335f9874d1ab)

## Acceptance criteria
- [ ] Show search tags underneath the input field on the left instead of inside the input field on the right

## Locations to be impacted
**please complete this list when working on this issue**
- Global search
- Membership Suggestions (users with no memberships)
- Templates
- innovation-library
- Community contributors block

**Comment by alstojanovic** [comment]
I think it is better to have the terms as start adornment because in some places like community contributors block we use search as an inline element. If we would put the terms underneath the search it would not look nice.
This is with terms as a start adornment:
<img width="824" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2lvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39c752a933c47460cecc8e7ff5f6e2eef73296b5/image.png" alt="image.png" />
Also if we have the terms at start it will be in accordance with the Explore challenges search/filter that uses terms as start adornments.
<img width="1233" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd21vQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3647e9148828f7881d0245212dc19cf49219837c/image.png" alt="image.png" />

The search on explore challenges is a different component than the search that is used everywhere else. Do we sync the tag colors to be the same on these 2 components?

**Comment by SimoneZaza** [comment]
@alstojanovic, Indeed, left is already much better than right and it is very clear that these search terms are part of your search. However, on smaller screens, these tags fill up the search bar and there is little or even no room left to place the cursor and add additional search terms.

**Comment by alstojanovic** [comment]
@Comoque1 we agreed that for smaller inline search boxes the terms stay inside and that for bigger search input fields they be moved underneath.
Small search inputs: Community contributors block, innovation-library, templates
Big search inputs: All others underneath

**Comment by Comoque1** [comment]
@alstojanovic when there are multiple search terms in "community contributors" block, they are not within the search.
<img width="1420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN095QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--339a8cdb9d7c86b4af5cf30749340b9386936a07/image.png" alt="image.png" />

**Comment by alstojanovic** [comment]
I saw this, it is an old bug.
@SimoneZaza  Do we address this now? This happens because the reserved space for the chips is 40%. They basically cannot fit. I can make it slightly better by increasing the max width for the chips to be like 70 or 80% but it still won't help if the words are too big.
The best looking solution may be to hide some of the terms as a '+2 more' tooltip like we do with tags.

**Comment by Comoque1** [comment]
Raised a separate [issue](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5688) regarding my last comment and closing this one.
