### ISSUE TITLE
Upgrade to Excalidraw v0.17.0

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#5196]
## Description

As a user I want the best whiteboard experience

## Acceptance criteria

- [ ] Evaluate impact of moving to v0.17.0
- [ ] Migrate to this version
- [ ] Explore usage of frames / comments which are now available on excalidraw+

## Additional Context
The whiteboards are seeing significant usage, good to get the latest excalidraw features + fixes

https://github.com/excalidraw/excalidraw/releases/tag/v0.17.0

**Comment by SimoneZaza** [comment]
Note that this potentially becomes a much bigger issue, especially because of:

**Breaking Changes**

- The Ref support has been removed in v0.17.0 so if you are using refs, please update the integration to use the excalidrawAPI #7251.

- Additionally ready and readyPromise from the API have been discontinued. These APIs were found to be superfluous, and as part of the effort to streamline the APIs and maintain simplicity, they were removed in version v0.17.0 #7251.
