### ISSUE TITLE
BUG: Crowdin step part of the build not working

### ISSUE THREAD

**Issue by hero101** [alkem-io/client-web#5198]
Currently, the translations are not merged into the code base, nor released.
Crowdin provides a couple of ways to do that, via the github integration, a github action, or just manually.

## Acceptance criteria
- the translations to be included automatically in the released version
- the ability to add the translations to the code base (not manual)

**Comment by hero101** [comment]
@SimoneZaza 
This is causing the translations to not be picked up as part of the version. I tried to make it automatically a while back but it did not go well.

**Comment by valentinyanakiev** [comment]
@hero101 I don't believe the integration is properly set up. It requires Github authorization of Crowdin, so Crowdin has sufficient privileges to do actions over our repository. It creates a Crowdin bot that should be able to open PRs etc. The sync github --> crowdin is possible because the project is public.
