### ISSUE TITLE
BUG: Text message Opportunity Innovation Flow

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#5205]
**Describe the bug**
wrong text in innovation flow

**To Reproduce**

1. Go to any opportunity
2. and look at the next innovation flow state

**Expected behavior**
In the translation file not to have a hardcoded "Challenge" but instead the variable for the journey type

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHpmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e91189527d0ef0708794a03553f2c9fd08a9a71/image.png)
<img width="1080" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVY5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--890dfeeea7eb2c3da9dbff48690a320d91e79525/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
<img width="1080" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVY5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--890dfeeea7eb2c3da9dbff48690a320d91e79525/image.png" alt="image.png" />
There is only one version in the translation file.. Can we change Challenge into something like {{journeyType}}? Otherwise we might need a separate translation string in here for opportunities.

**Comment by SimoneZaza** [comment]
...or do we just delete the entire thing? As we've discussed previously, many people currently use different states simultaneously, and the message is quite strong..

**Comment by SimoneZaza** [comment]
Suggestion: remove text, add icon to active state button

**Comment by Comoque1** [comment]
When switched to another language, challenge is returned
<img width="1866" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2dWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ce2524474494497058ed50eb89971639922c163/image.png" alt="image.png" />

**Comment by ccanos** [comment]
That is normal, the other translation files are not touched, they will be updated when we merge with the crowdin jsons.
