### ISSUE TITLE
New Memberships block: UI Improvements

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5477]
## Description

As a user, I want a dashboard that looks peaceful to the eye through consistency between the blocks.

## Acceptance criteria
After the nice refresh of the Recent Contributions blocks, it would be great to have consistens styling for the New Memberships block:
### Sections
- [x] Split the first section (Open applications & invitations) into 2, so it becomes:
- Open Invitations
- Open Applications
- Recently Joined 
- [x] If there are no invitations or applications, don't show these sections
- [x] Position the badge behind "Open Invitations", and count only the open invitations (since these are the only ones that require action from the user). Count **all open invitations**, not just the ones that are visible (which can happen when there are more than 4)
- [x] As we currently do: fill up potential white space if there are no open invitations/applications with recently joined
- [x] (might take bug #5377 directly into consideration?)
### Cards
- [x] First line: Journey title (Remove starting sentences "You are invited to join" and "You applied to join") **truncate to fit on one line**
- [x] Second line: content as is, but not italic, exactly the same as the contribution blocks.
- [x] Behaviour as the cards in the contributions block: light grey background on hover
### Footer
- [x] Change text to: "All pending memberships"

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
@ccanos clicking on `All pending memberships` opens `My memberships` dialog, instead of `Pending memberships`
<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGM2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--968f19f126ac822ed23f823b7963430c26fe457e/image.png" alt="image.png" />

<img width="980" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGs2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b87f9ad8ce9527ffecf9eee967fc417ef5859470/image.png" alt="image.png" />
