### ISSUE TITLE
New Forum Category: Releases

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5625]
## Description

As a GA, I want to group all release notifications in 1 category

## Acceptance criteria

- [x] Add category to the forum: Releases
- [x] Icon: import CelebrationIcon from '@mui/icons-material/Celebration';
- [x] Client shouldn't show this category when creating a discussion to people without global admin priviliges

## Additional Context
- Set as false on server
- Unhide it on the client for Global admins

**Comment by alstojanovic** [comment]
@SimoneZaza what does "Set as false on server" mean?
The discussion categories are stored as a simple string array. We are going to add the Releases to this string and then filter it out on the client based on user privilege.
Additionally I think we need to have a privilege check on the server so that no one tries to create a release category discussion through the API.

**Comment by SimoneZaza** [comment]
@alstojanovic if I remember correctly, @me-andre suggested this during the refinement, can you check with him? Thanks!

**Comment by Comoque1** [comment]
Works as per AC.
