### ISSUE TITLE
BUG: Text/shapes get disconnected when importing whiteboard template

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5715]
**Describe the bug**
When loading a template from the library, the text inside the shapes are disconnected from the shapes. It seems to have "unbinded the text from the shape" (This option can be found when right clicking on a shape with text). These textblocks where created by double-clicking on a shape and then adding text. This works perfectly. But when using the template, the text has become separate from the shape so isn't moving with it anymore, doesn't wrap anymore, etc etc

**Checked on 15/3:** 
- This is happening with all templates from both space and global library when I import them into a new whiteboard
- When updating older templates in the library, text is also decoupled from shape in this template
- When updating newer templates in the library, the text is not decoupled in this template

Spike: investigate 1-2 hours

**To Reproduce**

1. ...

**Expected behavior**

**Screenshots**

**Comment by Comoque1** [comment]
Tested with PROD template on dev env, but:
-  as visual and links are pointing to prod storage bucket the save was failing
-  this is a new template and the description was mentioned  that the problem is experienced with old ones.
Still, the text/shapes didn't disconnect

The fix will need additional verification on prod.
