### ISSUE TITLE
Recent contributions block is showing title twice

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6057]
## Description
<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1978df5069609e717a902dc2fea45513ff333f4/image.png" alt="image.png" />

## Acceptance criteria

- [ ] Take content out of block and display it in the dialog without border/title

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
> Now it is shown correct, but there are some misalignment with design: <img alt="image.png" width="2000" src="https://camo.githubusercontent.com/8e8d583f9e262160cf4bb399a254434e7a37a618278fac50ec0e2dd007fb81c0/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424d6b396d516b453950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d613465353133643532636632636664653935303732653736333435616533623930613763383531302f696d6167652e706e67">

A fix for the toggle position was applied - to be on the right. 
Initially, I thought it would be more prominent to be centered. 

Regarding the design:
1. The wording **Contributions** plus the state of the toggle **Most Recent** / **Most Active** seems enough.
2. The position of the toggle - in order to be in the dialog header we need to tightly couple the dialog view logic with the actual content logic as the switch is part of data filtering. So we're keeping it in the dialog content for now.

Let's discuss #1 & #2 and extract additional tickets if needed. The doubling content issue described in this one is fixed.

**Comment by Comoque1** [comment]
Looks ok on dev env.
