### ISSUE TITLE
BUG: When user has bigger membership, Spaces & Subspaces block shows all My Spaces

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6255]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/home
2. Spaces & Subspaces block, section: My Spaces: shows many memberships, which results in higher block
<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN01UQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--348dcb196cd5f1b84d7bf3d999c365147fff1acf/image.png" alt="image.png" />
<img width="920" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1FUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9cfe0a5a517d4ccbee157767046fb2127eba1175/image.png" alt="image.png" />

**Expected behavior**
_These are the slightly adjusted AC from the original issue when creating the Pending Memberships block, not sure if there were changes since then_
- [ ] First section: list of pending invitations
- [ ] Second section if the first section holds 0, 1, or 2 items: My memberships
- [ ] Third section if the first 2 sections hold 0, 1, or 2 items in total: Recently Joined
 More button if second section is shown: Show all my memberships, opens dialog
 More button if only first section is shown: Show all my pending memberships, opens pending memberships dialog (which is already on production)

**Comment by bobbykolev** [comment]
This is a corner case as only spaces created by you are shown. Regular users will see one to two (I guess) spaces.

**Comment by SimoneZaza** [comment]
@me-andre I fully agree with rethinking this block. However, giving the limited capacity that we have, I think we have other priorities to focus on. So if it's not too much time to reinstate/expand the original rules about how many items to show here, that would have my preference for now.

**Expected behavior**
_These are the slightly adjusted AC from the original issue when creating the Pending Memberships block, not sure if there were changes since then_
- [ ] First section: list of pending invitations
- [ ] Second section if the first section holds 0, 1, or 2 items: My memberships
- [ ] Third section if the first 2 sections hold 0, 1, or 2 items in total: Recently Joined
 More button if second section is shown: Show all my memberships, opens dialog
 More button if only first section is shown: Show all my pending memberships, opens pending memberships dialog (which is already on production)

**Comment by bobbykolev** [comment]
outdated
