### ISSUE TITLE
BUG: Error when posting comment after browser is inactive for a while

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6283]
**Describe the bug**
When the browser is left open for too long before adding a comment (or doing a different action like creating a post?), I get an error when posting. However, when I refresh the page, the comment is there.

When posting the comment:
<img width="1453" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVVqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c7a93c80881ca3654806a1b3cf1fd586eccd2b6/image.png" alt="image.png" />

Error in detail:
<img width="623" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWNqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--529d5a12ba25016cc814d56de16af660e41a2a79/image.png" alt="image.png" />

But the post is actually there when I refresh the page:
<img width="838" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bec707411029a9223a51dc7238220b85af2bbe4b/image.png" alt="image.png" />

**To Reproduce**

1. Go to any page
2. Keep it open for a long time (47 minutes worked for me to reproduce)
3. add comment

**Expected behavior**
No error, page to be refreshed

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by larssondenise** [comment]
This is also the case for a post in a call for posts, is it possible to prioritize this one? :) Happens a lot in the team but more importantly for users...  @techsmyth

**Comment by techsmyth** [comment]
@larssondenise I agree this is high priority.

**Comment by bobbykolev** [comment]
I put some effort in digging into the issue. It's easily reproducible but it requires time, so I have to leave it for now. It seems that the listener for particular comments disappear after some time. It could be because of performance optimization / garbage collection but this is speculative and it requires more time investment.

**Comment by bobbykolev** [comment]
Hello,

Here are some more findings/updates (technical) on the investigation:

1. The issue was **not** reproducible with killing/restarting of the server (excluding the theory of restarted instance causing the issue).
2. The state of the browser tab was tracked as suggested (here:)[https://developer.chrome.com/docs/web-platform/page-lifecycle-api#states] and there was **no** connection between the tab state and the missing subscription that updates the client state. States active->passive->hidden and back to active. 
3. The UNAUTHENTICATED error that sometimes pops up, seems **irrelevant** to the actual issue as the issue is reproducible every time and the error is not. In the local server logs, however, there was an `[auth] Access token has expired!` error which might be causing it. It's interesting that it was not returned as part of any of the graphql calls and the user remains authenticated. 

On the technical side, the issue was isolated to the `useRoomEventsSubscription` hook and its callback `onSubscriptionData` that is not called after the specified period (~40+ minutes). 

As the next steps, we raised two issues. One for updating the web socket library. And another one for logging the error / unsuccessful attempts.

**Comment by bobbykolev** [comment]
It looks like both the comments and callout creation are working as expected witht the fix. Tested after 3h
<img width="981" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEhHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d7f0f71621c79a433f2a0d546f653ab912556e8/image.png" alt="image.png" />
