### ISSUE TITLE
BUG: Callouts are created without collaborationId

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6314]
**Describe the bug**

**To Reproduce**

1. Go to alkem.io/home with a user that is member of Space 'building-alkemio-org'
2. Activity logs fail to load: ` "message": "Unable to find url path for collaboration: null",`
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVV3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd765c32a3a0441c29c0550c7f9077339f323cec/image.png" alt="image.png" />

**Expected behavior**
Activity logs a loading all related data.Add any other context about the problem here.

**Additional context**Add any other context about the problem here.

On 31st of May was experienced the same issue.
After investigation, it appeared that there was a callout created without collaborationId and the same callout was created second time successfully.
Need to investigate reasons for creating callout without collaborationId. It could be due slow internet connection or interruption during creation process..

5/6: It happened again to me (Simone) today, but this time with the "My Latest Contributions" block instead of the Latest Contributions in My Spaces. This is interesting since I haven't been doing anything on the platform today or yesterday, and I don't recall seeing this error on Monday afternoon. At least I know for sure that at 17.34 I didn't see this error, and I can't recall doing anything on the platform after that (but of course I may have forgotten about it..)
<img width="1720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0U1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2b08d8bc19c7896837f017fad7b561d9a3008f8/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
It happened again to me today, but this time with the "My Latest Contributions" block instead of the Latest Contributions in My Spaces. This is interesting since I haven't been doing anything on the platform today or yesterday, and I don't recall seeing this error on Monday afternoon. At least at 17.34 I didn't see this error, and I can't recall doing anything on the platform after that (but again, of course I may have forgotten about it..)
<img width="1720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0U1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2b08d8bc19c7896837f017fad7b561d9a3008f8/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
The fixes regarding this bug have been tested locally and on DEV env.
Haven't been able to reproduce them, but I wasn't able to identify concrete steps to reproduce, beforehand as well.
Closing for now and we'll monitor.
