### ISSUE TITLE
BUG: VC refers to Challenge

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6419]
**Describe the bug**
in the references they mention Challenge instead of Subspace which makes it unclear for the user 

**To Reproduce**

1. https://alkem.io/suzannedemospace/challenges/project/collaboration/example

**Expected behavior**
The text should state "Subspace" and not Challenge

**Comment by Comoque1** [comment]
The issue is still reproducible on acc env: https://acc-alkem.io/vesp/collaboration/test
<img width="1239" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWFlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--769f0d25cdfa5204e0daeeb6fe7daafe4ae98104/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Issue is still reproducible on ACC env.
<img width="1362" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE85QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b15056da9a2e4da2eff280c7975cc9fd5278ea4/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Comoque1 it is only in the sources that I am concerned with. It it is in teh text, and you have fed it with information about Alkemio then that is fine.

**Comment by techsmyth** [comment]
Also important to re-ingest if this is still showing up
