### ISSUE TITLE
Account tab 1: organizations, view only

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#6440]
## Description

As a user I want to be able to manage my account and the entities it contains

### Organization profile 
- [ ] Account tab with 4 blocks: 
- Spaces (top left)
- VCs (top right)
- Innovation Packs (bottom left)
- Custom homepages (innovation hubs) (bottom right)
---
- [ ] Spaces:
- Horizontal space card with avatar, title, tagline
- Clicking on this brings user to Space Dashboard
- [ ] Virtual Contributors:
- Horizontal space card with avatar, title, tagline
- Clicking on this brings user to VC Profile (not the profile settings!)
- If the user/organization has multiple accounts, show related account for the VC
- [ ] Innovation Packs:
- Only show when there are innovation packs hosted by this organization
- Horizontal space card with icon, title, tagline, and contents (= same content as used for innovation pack card used in space library!)
- Clicking on this brings user to Innovation pack (profile) page (not the settings!)
- If the user/organization has multiple accounts, show related account for the IP
- [ ] Custom Homepages:
- Only show when there are custom homepages hosted by this organization
- Horizontal space card with icon, title, tagline, and contents (= same content as used for innovation pack card used in space library!)
- Clicking on this brings user to custom homepage in a new tab (since they can't go back from there)
- If the user/organization has multiple accounts, show related account for the CH

## Additional Context

Figma (disregard the designs that are not part of this issue): https://www.figma.com/design/l0hLyZCBs5cxhpp5vUPAte/Account-page?node-id=186-106&t=AhyNIs3ukaS3wWt7-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
As part of this task we agreed on removing the Create InnovationPack option in the Global Administration.

**Comment by Comoque1** [comment]
### Organization profile - **OK**
- [ ] Account tab with 4 blocks: 
- Spaces (top left)
- VCs (top right)
- Innovation Packs (bottom left)
- Custom homepages (innovation hubs) (bottom right)
<img width="1201" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWhIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c0b199bdaa852c7367cb79feb43287aa36f2213/image.png" alt="image.png" />

---
- [ ] Spaces: **OK**
- Horizontal space card with avatar, title, tagline
- Clicking on this brings user to Space Dashboard
- [ ] Virtual Contributors: 
- Horizontal space card with avatar, title, tagline - **OK**
- Clicking on this brings user to VC Profile (not the profile settings!) - **Clicking doesn't do anything**
- If the user/organization has multiple accounts, show related account for the VC- **There is no split for multiple account**
- [ ] Innovation Packs:
- Only show when there are innovation packs hosted by this organization - **Shown even when there are no innovation packs**
- Horizontal space card with icon, title, tagline, and contents (= same content as used for innovation pack card used in space library!) - **The icons for different templates are missing**
<img width="1086" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekJIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d551fa041c07be1bf95a2c7bd9545179922974f9/image.png" alt="image.png" />

- Clicking on this brings user to Innovation pack (profile) page (not the settings!)- **OK**
- If the user/organization has multiple accounts, show related account for the IP- **There is no split for multiple account**
- [ ] Custom Homepages:
- Only show when there are custom homepages hosted by this organization - **OK**
- Horizontal space card with icon, title, tagline, and contents (= same content as used for innovation pack card used in space library!) - **OK**
- Clicking on this brings user to custom homepage in a new tab (since they can't go back from there)- **clicking on the use the same tab and brings the user to the custom homepage settings page**
- If the user/organization has multiple accounts, show related account for the CH

**Comment by Comoque1** [comment]
Tested OK on DEV env.
The only thing not addressed is: If the user/organization has multiple accounts, show related account for the CH, AND VC etc.
There is no design. In addition as we move towards multiple data types per account, this will not be valid anymore.
