### ISSUE TITLE
VCs visible in Community and About

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6473]
## Description

As a user, I want to see which VCs are part of this space

## Acceptance criteria

- [ ] Block on community tab in space
- [ ] Block on contributors dialog in Subspace
- [ ] Listing a max of 3 VCs to be shown, more when opening dialog
- [ ] VCs visible under the contributors block in the About dialog
- [ ] If no VCs then do not show the block
- [ ] If VC is ~private~* / hidden, do not show in the About dialog (possible?)
- [ ] Only show the block if the user has READ access to the space/subspace

*UPDATE 10.7.2024
- [ ] Show **all non-hidden** VC members. As we have Public, Account, and Hidden, the ones with Account visibility (private) are relevant members of that community. It could be changed in the future.

## Additional Context

https://www.figma.com/design/uLeMa7XLabwFSy8vtZ35Fl/VC-visible-in-space%2Fsubspace?node-id=16-2

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by jeroentskui** [comment]
if no vc is in the space the block/widget is not shown

**Comment by EmiliaPavlova** [comment]
@jeroentskui, @larssondenise, there's no design for the See more dialog. What data do we want to show there? <img width="1557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkM1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62935584e6b61eaf5cf13bd0632e0395ca6fd365/Screenshot%202024-07-05%20at%2018.45.12.png" alt="Screenshot 2024-07-05 at 18.45.12.png" />

**Comment by jeroentskui** [comment]
@EmiliaPavlova haha good catch i forgot to add that; ive added a design screen for the read more dialouge for the space level; and also described the interaction of what happens if you click on a vc ave also added the tagline to the block as its visible in the space level. at some point in the near future i hope we can do a update to the contributors block on subspaces to make it mroe similar to this pop up for spaces (so we can also actually show people names as text and display subtitle of the vc's but i felt doing that now would explode this ticket out mroe than scoped. 

https://www.figma.com/design/uLeMa7XLabwFSy8vtZ35Fl/VC-visible-in-space%2Fsubspace?node-id=16-2

<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1MrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--662900e1c53c3dfcf2ba2d9e62224b19d417ade1/VC%20visible%20in%20the%20Space%20community%20page%20Read%20More%20Dialouge.png" alt="VC visible in the Space community page Read More Dialouge.png" />


i h

**Comment by EmiliaPavlova** [comment]
We don't display contributors in Space About dialog, so VC is not added there either.
