### ISSUE TITLE
Remove My Latest Contributions

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#6531]
## Description

As a user I do not need to see the Latest Contributions block in case of no contributions

## Acceptance criteria

- [ ] Do not show My Latest Contributions when there are none

## Additional Context
<img width="1239" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU8wQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b68f9f5370c140d914d8c6aab2aad23408bc6c01/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by larssondenise** [comment]
@bobbykolev

**Comment by bobbykolev** [comment]
In the case you've listed is fine - new user no memberships, but otherwise there's a hole in the page:
<img width="1180" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2kwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c0de87dda6ea8b24829d350affddfc00abebe51/Screenshot%202024-07-04%20160728.png" alt="Screenshot 2024-07-04 160728.png" />

Are you sure we're removing it either way? @larssondenise
