### ISSUE TITLE
Option to embed iframe in MD editor

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6607]
## Description

As a user I want to be able to embed a video from youtube into my post. As a user with a new Space, seeing these cool Arcade click-throughs, I want it even more!

## Acceptance criteria
Server:
- [ ] Extend the Markdown scalar type to detect iframe usage, plus
- [ ] check against list of approved domains (see below)

Client:
- [ ] Add button to MD editor, next to the image button 
- import SmartScreenOutlinedIcon from '@mui/icons-material/SmartScreenOutlined'; <img width="53" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDdpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--160399ec5b370283847403df9ef68268b56d997a/image.png" alt="image.png" />

- label: Embed Video
- [ ] Clicking on the button opens a small dialog in which the user can paste the iframe code
- Title: Embed Video or other Media
- Text: Copy the embed/iframe code below
- Large input field
- Buttons: Cancel; Insert
 
- [ ] Validation in the client, mailto link to support@alkem.io in the validation error. 
- Text: "Unfortunately, this code is not supported. Please check the code carefully or contact support@alkem.io"

Approved domains:
- Youtube
- Vimeo, 
- Arcade
- Issuu
- 
UPDATE 17.12.2024 - 
- [ ] add Canva to the list of allowed sources (see comments)

## Additional Context
Timebox to 5

The result should look something like this:
<img width="973" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGYwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da552df9b15af4661713ef724ebae6ffdb7c0703/image.png" alt="image.png" />

I found this on the tiptap website, not sure it can be used since it's still in experimental phase: https://tiptap.dev/docs/examples/experiments/iframe

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@SimoneZaza am concerned about this one, lets chat it through.

**Comment by SimoneZaza** [comment]
As discussed with @bobbykolev, here are some embedding codes from the different platforms mentioned in the AC:

Vimeo:
<iframe title="vimeo-player" src="https://player.vimeo.com/video/784939656?h=3298c9119d" width="640" height="360" frameborder="0"    allowfullscreen></iframe>

Arcade:
<div style="position: relative; padding-bottom: calc(40% + 41px); height: 0; width: 100%;"><iframe src="https://demo.arcade.software/5fvizP4ekEOya5CGHIwa?embed&show_copy_link=true" title="Subpace Collaboration Tools" frameborder="0" loading="lazy" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="clipboard-write" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;color-scheme: light;"></iframe></div>

Issuu (not 100% sure as I am not able to get one without a paid account):
<iframe allowfullscreen allow="fullscreen" style="border:none;width:100%;height:326px;" src="//e.issuu.com/embed.html?backgroundColor=%23ebb88a&backgroundColorFullscreen=%23ebb88a&d=orange_juice_issue_1_b0ceb817d77d59&hideIssuuLogo=false&hideShareButton=true&pageNumber=6&u=ds_demo"></iframe>

**Comment by reactoholic** [comment]
Additional information regarding the implementation of the embed code functionality:

The task's implementation timeline was extended due to several factors that became apparent only after work on injecting the iframe into the markdown editor began. 

1. **Initial Investigation**: An investigation was conducted to determine how to inject an iframe into our markdown editor using the libraries we currently utilize. The conclusion was that the `tiptap` library supports such integration, but only in an experimental phase. This required custom adjustments to its extensions, which added complexity and time.

2. **HTML Sanitization Issues**: The integration of embed code faced challenges due to a library (`rehype`) that sanitizes HTML within the editor. Custom configurations were necessary to address this, which took additional time but were ultimately successful.

Currently, there are two unresolved issues related to the iframe functionality:  
- When adding an embed code, the iframe is always inserted at the top of the content.  
- Only one iframe can be included in a comment. Attempting to add another overwrites the existing one.

**Comment by reactoholic** [comment]
The origin prop from the embed code from `issuu.com` has strange structure and our current implementation doesn't accept it. I've set the status of the ticket to "In progress" since I'm on fixing this issue.

**Comment by Comoque1** [comment]
Tested on ACC env.
Tested MD locations:
 - Context
 - Callouts
 - Community updates
 - Forum Discussion - raised [bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/7343)
 - Templates
 - User profile
 - Calendar event
 - Messaging

Issuu - embedded, but no data was displayed.

**Comment by bobbykolev** [comment]
Canva (www.canva.com) added to the allowed src as requested by @SimoneZaza 

```
<iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https://www.canva.com/design/DAGZjbaYpVc/_TcjLJQIUnLnrssRxI0vUA/view?embed" allowfullscreen="allowfullscreen" allow="fullscreen">
</iframe>
```

**Comment by Comoque1** [comment]
Latest update works OK on ACC env.
