### ISSUE TITLE
BUG: When copy mentioned User/VC in the question, SQL error is thrown

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6622]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/j25/knowledge-base
2. In a post callout mention a VC and add the VC in the question as well (i.e. **@music** @music what is the type of music, the band is playing?)
3. Error is thrown: `"message": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1",`
<img width="1567" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFB1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f699ba38fe5e23629acbb9989d1a4b2de4737482/image.png" alt="image.png" />

**Expected behavior**
SQL error is is not thrown

## Additional information:
This message generates these variables: `@Evgeni Dimitrov @Evgeni Dimitrov @Evgeni Dimitrov what is the type of music, the band is playing?`
```
{
  "communityId": "ada83ce1-97f5-4807-b350-6286a266737d",
  "filter": {
    "email": "Evgeni Dimitrov what is the type of music, the band is playing?\n\n",
    "displayName": "Evgeni Dimitrov what is the type of music, the band is playing?\n\n"
  },
  "first": 30,
  "includeVirtualContributors": true
}
```

**Comment by techsmyth** [comment]
High priority, a lot of users will try copy + pasting. Need to look at either how the copy is done or how the paste happens...

**Comment by bobbykolev** [comment]
It's in the client where, once we detect the '@' symbol, we're trying to retrieve the users (usersPaginated) but  providing the entire string. This isn't trivial because, in the regular flow, the user receives suggestions and selects a name from a list manually. When pasting, however, we need to either determine who the mentioned contributor is or simply ignore the '@'. Currently, we do the second one, but we need to stop making the failing request.

**Comment by bobbykolev** [comment]
It seems that only the '?' symbol is causing the issue. Easily reproducible without pasting, just put '?' after the '@'.
 
In order to handle this situation (not only*), the following validation was added. In the case of:
- Invalid chars (.?%_);
- too many empty spaces (> 2);
- too long mention string (> 30);
skip the usersPaginated request and do not suggest mentions.

As this validation is a bit stronger, @SimoneZaza , @techsmyth please confirm that you're fine with it. 
We lack such validation for our entity names. So it's possible to have names with these symbols and many empty spaces. Still, this is my suggestion for limiting the available input for contributors' suggestions.

**Comment by SimoneZaza** [comment]
As discussed, I agree, with the note that we should then prevent users from using these characters in their user name, but this we can do as part of a different story that we address (a little) later.

**Comment by bobbykolev** [comment]
Ok, for completing this issue we're applying the validations described in my previous comment, but limiting the invalid chars only to '?'. I'll extract another story for validation of both the input during name creation and then on the mentions serach.

**Comment by Comoque1** [comment]
Closing the issue.
I've hit 1 more case, when the request fails `@'  `, which we could address in the followup story.
