### ISSUE TITLE
BUG: User is able to remove all post on the creation flow

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#6737]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/home with user that is part of VC campaign flow
2. Fill up the required fields 
3. Select Written Knowledge flow 
4. Press create button
5. On the dialog "Add knowledge", user is able to remove all "posts", which will result in no knowledge for the VC
<img width="1380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEpJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--520210f473f13b0b0eaa5c95322517ca67bbe44e/image.png" alt="image.png" />

**Expected behavior**
The easiest option of the following two:
- [ ] Disable/hide delete button if there is only one post (eg the default post when no extra posts are added, or another post when there were multiple and a couple ,including the default one, were deleted)
- [ ] If the deletebutton is disabled but not hidden, add tooltip "At least one post is needed to continue"
or
- [ ] Disable the continue button when there are no posts (default post and optional others are deleted)
- [ ] Add tooltip for disabled continue button: "Add at least one post to continue"

**Comment by EmiliaPavlova** [comment]
Added requirement for at least 1 post - the delete icon is not present if there is only one post. Also is added a functionality for disabling `Continue` button with the mentioned in the task tooltip if there are no posts, although this variant is not possible to be reproduced since the last post cannot be deleted.
And as per discussion is now set a limit of 25 posts. If reached, the `Add another post` button becomes disabled and the tooltip text is changed to "More posts can be added in the Body of Knowledge once the VC is created".

**Comment by hero101** [comment]
Just adding my input: The dialog states "You can update, add, and remove content later.", so why must we require atleast one Post?

**Comment by Comoque1** [comment]
Tested OK on DEV env.
@hero101 the reason for having at least one post is, it to be used as BoK for "Try it out" dialog.
