### ISSUE TITLE
Simple homepage: Explore spaces block

### ISSUE THREAD

**Issue by bobbykolev** [alkem-io/client-web#7079]
## Description

As a user who starts using Alkemio as part of the VC Campaign (or any other future campaign), I expect to see something about the VCs directly

## Acceptance criteria
  - [ ] Explore spaces block that is also used on dashboard for unauthenticated users (#6943) > we may need to tweak this a little bit with respect to the filters
  - Figma: https://www.figma.com/design/kA1NFl2zU8CdiIbdvuzRTk/Alkemio-Home-Page?node-id=344-413&t=58RTC3BT0xgKmyW1-1

## Additional Context
<img width="870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemh1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a62eaaed4fa68fc9bb1e6c5fbf8642df229a84d/invites.jpg" alt="invites.jpg" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
@SimoneZaza  do you want the new filter treatment to take place in the Unauthenticated page as well, or you want the dropdown only here?

**Comment by SimoneZaza** [comment]
@bobbykolev depends on what the final implementation is. I'm not a big fan of this filter dropdown, it's just there because we don't have enough space for all filters with the menu on the left. So if we can think of something better then that could also be implemented on the page for unauthenticated users, but if the filters remain invisible upon first sight like in this design, I would prefer the page for unauthenticated users to remain as is. If this is adding a lot of complexity, please touch base :)

**Comment by bobbykolev** [comment]
I'll leave the filter changes for now. Let's have everything in place and then we can refine it.
<img width="1157" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3B2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb033ffd26a882a5eccc08d0c951be7e6cfb6de2/Alkemio-Safe-Spaces-for-Collaboration-10-24-2024_05_32_PM.png" alt="Alkemio-Safe-Spaces-for-Collaboration-10-24-2024_05_32_PM.png" />
