### ISSUE TITLE
BUG: User can set space URL for subspace template creation

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7133]
**Describe the bug**

**To Reproduce**

1. Go to https://sandbox-alkem.io/innovation-packs/e-pack/settings
2. Press "Create subspace" template button
3. Add link to a "SPACE" 
4. Press: "Use this space" button - all space callouts are added
<img width="1019" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd09SQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58a7560c35900e0ccb40ee32dccaa1e13f897515/image.png" alt="image.png" />
<img width="1328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG1SQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94caea6ed398d72affbe7176e287f46739c4e59e/image.png" alt="image.png" />

**Expected behavior**
Change URL description to "Enter the url of the Subspace" instead of Space or Subspace

**Comment by ccanos** [comment]
@SimoneZaza is this not okay as is?
Evgeni was concerned because a user can paste a space url in this field and make a template of a Space (not a subspace). That's technically possible, and not failing, the only problem is that Spaces have that dummy InnovationFlow with just 1 state saying "Not used" (see screenshot).
We can easily  (estimated as 1) limit that pasted url to only accept subspaces urls, should we?

**Comment by SimoneZaza** [comment]
@ccanos I think we can handle it even more simply by just changing the text to say "Enter the URL of the Subspace" instead of "Space or Subspace" :) 
Fine if they can enter a Space, but we shouldn't prompt them to.
